"""Conformal classification prediction-set stability example.

The example audits whether aggregate conformal prediction-set quantities are
stable to hidden subgroup recomposition. It is synthetic and dependency-free:
class probabilities are generated by a small deterministic scoring rule, a
split-conformal score threshold is computed from calibration rows, and
``updatesupport`` audits prediction-set size, ambiguous-set rate, coverage,
miscoverage, and risky-label containment.

Run from the repository root with:

    uv run python examples/conformal_classification_stability.py

Optionally write the Markdown report:

    uv run python examples/conformal_classification_stability.py \
        --output data/conformal_classification_stability.md
"""

from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path
from typing import Any, Mapping, Sequence

if __package__ is None or __package__ == "":
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import updatesupport as us


CLASSES = ("approve", "review", "reject")
POSITIVE_LABEL = "reject"
PUBLIC_COLUMNS = ("product_area", "region", "customer_tier")
HIDDEN_REFINEMENTS = (
    "acquisition_channel",
    "tenure_band",
    "device_type",
    "language",
)
HIDDEN_COLUMNS = PUBLIC_COLUMNS + HIDDEN_REFINEMENTS
CANDIDATE_REFINEMENTS = HIDDEN_REFINEMENTS
WEIGHT_COLUMN = "cases"
OUTCOME_COLUMN = "observed_outcome"
ALPHA = 0.10
CONFORMAL_THRESHOLD_BUFFER = 0.06

_PRODUCT_AREAS = ("checkout", "onboarding", "support")
_REGIONS = ("north_america", "europe", "latam")
_TIERS = ("enterprise", "midmarket", "smb")
_CHANNELS = ("sales_led", "partner", "self_serve", "affiliate")
_TENURES = ("new", "established")
_DEVICES = ("desktop", "mobile")
_LANGUAGES = ("english", "localized")


def synthetic_classification_rows() -> list[dict[str, Any]]:
    """Return retained reporting cells for the classification stability audit."""

    specs = [
        (
            "checkout",
            "north_america",
            "enterprise",
            "sales_led",
            "established",
            "desktop",
            "english",
            "approve",
            780,
        ),
        (
            "checkout",
            "north_america",
            "enterprise",
            "partner",
            "new",
            "mobile",
            "localized",
            "review",
            360,
        ),
        (
            "checkout",
            "europe",
            "midmarket",
            "partner",
            "established",
            "desktop",
            "english",
            "approve",
            620,
        ),
        (
            "checkout",
            "europe",
            "midmarket",
            "affiliate",
            "new",
            "mobile",
            "localized",
            "reject",
            300,
        ),
        (
            "checkout",
            "latam",
            "smb",
            "self_serve",
            "new",
            "mobile",
            "localized",
            "reject",
            520,
        ),
        (
            "checkout",
            "latam",
            "smb",
            "partner",
            "established",
            "desktop",
            "english",
            "review",
            340,
        ),
        (
            "onboarding",
            "north_america",
            "enterprise",
            "sales_led",
            "established",
            "desktop",
            "english",
            "approve",
            690,
        ),
        (
            "onboarding",
            "north_america",
            "enterprise",
            "self_serve",
            "new",
            "mobile",
            "english",
            "review",
            310,
        ),
        (
            "onboarding",
            "europe",
            "midmarket",
            "partner",
            "new",
            "mobile",
            "localized",
            "review",
            470,
        ),
        (
            "onboarding",
            "europe",
            "midmarket",
            "sales_led",
            "established",
            "desktop",
            "english",
            "approve",
            520,
        ),
        (
            "onboarding",
            "latam",
            "smb",
            "self_serve",
            "new",
            "mobile",
            "localized",
            "reject",
            590,
        ),
        (
            "onboarding",
            "latam",
            "smb",
            "affiliate",
            "established",
            "desktop",
            "localized",
            "review",
            280,
        ),
        (
            "support",
            "north_america",
            "enterprise",
            "partner",
            "established",
            "desktop",
            "english",
            "review",
            450,
        ),
        (
            "support",
            "north_america",
            "enterprise",
            "self_serve",
            "new",
            "mobile",
            "localized",
            "reject",
            240,
        ),
        (
            "support",
            "europe",
            "midmarket",
            "partner",
            "established",
            "desktop",
            "localized",
            "review",
            500,
        ),
        (
            "support",
            "europe",
            "midmarket",
            "affiliate",
            "new",
            "mobile",
            "localized",
            "reject",
            330,
        ),
        (
            "support",
            "latam",
            "smb",
            "self_serve",
            "new",
            "mobile",
            "localized",
            "reject",
            610,
        ),
        (
            "support",
            "latam",
            "smb",
            "sales_led",
            "established",
            "desktop",
            "english",
            "review",
            260,
        ),
    ]
    columns = HIDDEN_COLUMNS + (OUTCOME_COLUMN, WEIGHT_COLUMN)
    return [dict(zip(columns, row, strict=True)) for row in specs]


def fit_conformal_threshold(
    *,
    alpha: float = ALPHA,
    threshold_buffer: float = CONFORMAL_THRESHOLD_BUFFER,
) -> float:
    """Return the split-conformal class-probability inclusion threshold."""

    calibration_rows = _synthetic_calibration_rows()
    nonconformity_scores = []
    for row in calibration_rows:
        probabilities = _class_probabilities(row)
        true_probability = probabilities[str(row[OUTCOME_COLUMN])]
        nonconformity_scores.append(1.0 - true_probability)
    q_hat = _conformal_quantile(nonconformity_scores, alpha=alpha)
    return max(0.0, min(1.0, 1.0 - q_hat - float(threshold_buffer)))


def build_conformal_result(
    rows: Sequence[Mapping[str, Any]] | None = None,
    *,
    alpha: float = ALPHA,
) -> us.ConformalAdapterResult:
    """Attach conformal prediction sets to retained classification cells."""

    rows = synthetic_classification_rows() if rows is None else rows
    threshold = fit_conformal_threshold(alpha=alpha)
    prediction_sets: list[tuple[str, ...]] = []
    predictions: list[str] = []
    y_true: list[str] = []
    for row in rows:
        probabilities = _class_probabilities(row)
        prediction = max(CLASSES, key=lambda label: probabilities[label])
        prediction_set = tuple(
            label for label in CLASSES if probabilities[label] >= threshold
        )
        if not prediction_set:
            prediction_set = (prediction,)
        predictions.append(prediction)
        prediction_sets.append(prediction_set)
        y_true.append(str(row[OUTCOME_COLUMN]))

    result = us.adapt_conformal_classification(
        rows,
        prediction=predictions,
        prediction_sets=prediction_sets,
        y_true=y_true,
        positive_label=POSITIVE_LABEL,
        source="split_conformal_classification",
    )
    metadata = dict(result.metadata)
    metadata["class_probability_threshold"] = threshold
    return us.ConformalAdapterResult(
        rows=result.rows,
        source=result.source,
        source_rows=result.source_rows,
        prediction_column=result.prediction_column,
        covered_column=result.covered_column,
        miscovered_column=result.miscovered_column,
        prediction_set_size_column=result.prediction_set_size_column,
        ambiguous_set_column=result.ambiguous_set_column,
        metadata=metadata,
    )


def build_stability_report(
    result: us.ConformalAdapterResult | None = None,
    *,
    include_attribution: bool = False,
) -> us.ConformalReportingStabilityReport:
    """Build the conformal classification reporting-stability report."""

    result = build_conformal_result() if result is None else result
    return result.reporting_stability(
        public=PUBLIC_COLUMNS,
        hidden=HIDDEN_COLUMNS,
        weight=WEIGHT_COLUMN,
        candidate_refinements=CANDIDATE_REFINEMENTS,
        ambiguity_limits={
            "prediction_set_size": 0.30,
            "ambiguous_set": 0.20,
            "covered": 0.20,
            "miscovered": 0.20,
            "contains_positive_label": 0.25,
        },
        search="beam",
        beam_width=8,
        max_added_columns=2,
        max_evaluations=64,
        exact_required=False,
        include_attribution=include_attribution,
        title="Conformal Classification Reporting Stability Example",
    )


def render_report(
    *,
    include_attribution: bool = False,
) -> str:
    """Render the conformal classification example as Markdown."""

    result = build_conformal_result()
    report = build_stability_report(
        result,
        include_attribution=include_attribution,
    )
    rows = result.rows
    threshold = float(result.metadata["class_probability_threshold"])
    mean_set_size = _weighted_mean(rows, "prediction_set_size", WEIGHT_COLUMN)
    ambiguous_rate = _weighted_mean(rows, "ambiguous_set", WEIGHT_COLUMN)
    miscoverage_rate = _weighted_mean(rows, "miscovered", WEIGHT_COLUMN)
    positive_rate = _weighted_mean(rows, "contains_positive_label", WEIGHT_COLUMN)

    target_rows = {row["target"]: row for row in report.to_tables()["targets"]}
    size_row = target_rows["prediction_set_size"]
    ambiguous_row = target_rows["ambiguous_set"]
    positive_row = target_rows["contains_positive_label"]

    lines = [
        "# Conformal Classification Reporting Stability Example",
        "",
        "This synthetic demo sits downstream of a conformal classification "
        "workflow. A deterministic classifier emits class probabilities for "
        "`approve`, `review`, and `reject`; a calibration split turns those "
        "scores into conformal prediction sets; `updatesupport` then audits "
        "whether aggregate prediction-set claims survive hidden subgroup "
        "recomposition.",
        "",
        "The public report groups retained decisions by product area, region, "
        "and customer tier. The retained but not publicly reported cells also "
        "track acquisition channel, tenure, device type, and language.",
        "",
        "## What The Conformal Layer Supplies",
        "",
        f"- Nominal conformal miscoverage level: {ALPHA:.0%}",
        f"- Class-probability inclusion threshold: {threshold:.3f}",
        f"- Conservative threshold buffer: {CONFORMAL_THRESHOLD_BUFFER:.3f}",
        f"- Observed weighted mean prediction-set size: {mean_set_size:.2f}",
        f"- Observed weighted ambiguous-set rate: {_percent(ambiguous_rate)}",
        f"- Observed weighted miscoverage rate: {_percent(miscoverage_rate)}",
        f"- Observed weighted reject-label containment rate: {_percent(positive_rate)}",
        "",
        "Those are ordinary conformal-derived row targets. The review question "
        "is whether their aggregate values are stable when the public decision "
        "mix is fixed but retained hidden composition changes inside the "
        "public buckets.",
        "",
        "## Hidden-Composition Readout",
        "",
        "- Mean prediction-set size can move from "
        f"{size_row['lower']:.2f} to {size_row['upper']:.2f}.",
        "- Ambiguous prediction-set rate can move from "
        f"{_percent(ambiguous_row['lower'])} to "
        f"{_percent(ambiguous_row['upper'])}.",
        "- Reject-label containment can move from "
        f"{_percent(positive_row['lower'])} to "
        f"{_percent(positive_row['upper'])}.",
        "",
        "Plain English: conformal prediction sets express row-level uncertainty, "
        "but the aggregate operational burden can still be composition "
        "sensitive. A public report can say manual-review burden is modest, "
        "while hidden shifts in channel, tenure, device, or language mix make "
        "multi-label sets or reject-containing sets much more common.",
        "",
        "This is not a confidence interval for classifier accuracy. It is a "
        "representation-stability audit of conformal-derived reporting targets.",
        "",
        "## Multi-Target Stability Audit",
        "",
    ]
    lines.extend(_without_title(report.to_markdown()))
    return "\n".join(lines)


def _synthetic_calibration_rows() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for product_area in _PRODUCT_AREAS:
        for region in _REGIONS:
            for customer_tier in _TIERS:
                for acquisition_channel in _CHANNELS:
                    for tenure_band in _TENURES:
                        for device_type in _DEVICES:
                            for language in _LANGUAGES:
                                row = {
                                    "product_area": product_area,
                                    "region": region,
                                    "customer_tier": customer_tier,
                                    "acquisition_channel": acquisition_channel,
                                    "tenure_band": tenure_band,
                                    "device_type": device_type,
                                    "language": language,
                                }
                                row[OUTCOME_COLUMN] = _observed_label(row)
                                rows.append(row)
    return rows


def _class_probabilities(row: Mapping[str, Any]) -> dict[str, float]:
    logits = {
        "approve": 1.25,
        "review": 0.45,
        "reject": 0.10,
    }
    if row["customer_tier"] == "enterprise":
        logits["approve"] += 0.35
        logits["reject"] -= 0.15
    elif row["customer_tier"] == "smb":
        logits["approve"] -= 0.28
        logits["reject"] += 0.28

    if row["product_area"] == "support":
        logits["review"] += 0.42
        logits["reject"] += 0.22
    elif row["product_area"] == "checkout":
        logits["reject"] += 0.18

    if row["region"] == "europe":
        logits["review"] += 0.12
    elif row["region"] == "latam":
        logits["review"] += 0.15
        logits["reject"] += 0.30

    if row["acquisition_channel"] == "sales_led":
        logits["approve"] += 0.22
    elif row["acquisition_channel"] == "partner":
        logits["review"] += 0.24
    elif row["acquisition_channel"] == "self_serve":
        logits["review"] += 0.24
        logits["reject"] += 0.34
    elif row["acquisition_channel"] == "affiliate":
        logits["reject"] += 0.42

    if row["tenure_band"] == "new":
        logits["review"] += 0.22
        logits["reject"] += 0.22
    else:
        logits["approve"] += 0.18

    if row["device_type"] == "mobile":
        logits["review"] += 0.14
        logits["reject"] += 0.16
    if row["language"] == "localized":
        logits["review"] += 0.20
        logits["reject"] += 0.18

    if row["acquisition_channel"] == "self_serve" and row["tenure_band"] == "new":
        logits["reject"] += 0.20
    if row["region"] == "latam" and row["language"] == "localized":
        logits["reject"] += 0.14

    return _softmax(logits)


def _observed_label(row: Mapping[str, Any]) -> str:
    probabilities = _class_probabilities(row)
    if probabilities["reject"] >= 0.31:
        return "reject"
    if probabilities["review"] >= 0.33:
        return "review"
    key = "|".join(str(row[column]) for column in HIDDEN_COLUMNS)
    raw = sum((index + 1) * ord(char) for index, char in enumerate(key)) % 17
    if raw in {0, 1} and probabilities["review"] >= 0.26:
        return "review"
    return "approve"


def _softmax(logits: Mapping[str, float]) -> dict[str, float]:
    max_logit = max(logits.values())
    exp_values = {label: math.exp(value - max_logit) for label, value in logits.items()}
    denominator = sum(exp_values.values())
    return {label: value / denominator for label, value in exp_values.items()}


def _conformal_quantile(scores: Sequence[float], *, alpha: float) -> float:
    if not 0.0 < alpha < 1.0:
        raise ValueError("alpha must be between 0 and 1")
    if not scores:
        raise ValueError("scores must be non-empty")
    sorted_scores = sorted(float(score) for score in scores)
    rank = math.ceil((len(sorted_scores) + 1) * (1.0 - alpha))
    index = min(max(rank - 1, 0), len(sorted_scores) - 1)
    return sorted_scores[index]


def _weighted_mean(
    rows: Sequence[Mapping[str, Any]],
    target: str,
    weight: str,
) -> float:
    numerator = sum(float(row[target]) * float(row[weight]) for row in rows)
    denominator = sum(float(row[weight]) for row in rows)
    return numerator / denominator


def _without_title(markdown: str) -> list[str]:
    lines = markdown.splitlines()
    if lines and lines[0].startswith("# "):
        lines = lines[1:]
        if lines and not lines[0]:
            lines = lines[1:]
    return lines


def _percent(value: float) -> str:
    return f"{100.0 * value:.2f}%"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        help="Optional Markdown output path.",
    )
    parser.add_argument(
        "--include-attribution",
        action="store_true",
        help="Include Shapley-style refinement attribution in the audit.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    markdown = render_report(include_attribution=args.include_attribution)
    if args.output is None:
        print(markdown)
        return
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(markdown + "\n", encoding="utf-8")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
