"""Representation adequacy and transport-stability auditing in Python."""

# ruff: noqa: F401

from importlib.metadata import PackageNotFoundError, version

from .adapters import (
    EstimatorAdapterResult,
    adapt_dataframe_effects,
    adapt_doubleml_effects,
    adapt_dowhy_effects,
    adapt_econml_effects,
)
from .breakdown import (
    BreakdownCurvePoint,
    BreakdownPointReport,
    breakdown_point,
)
from .certificate import (
    RepresentationStabilityCertificate,
    certify_public_representation,
)
from .claim import (
    ClaimAudit,
    ClaimNode,
    ClaimNodeAudit,
    ClaimRefinementRecommendation,
    ClaimSpec,
    ClaimTree,
    ClaimTreeAudit,
    DecisionResult,
    DecisionRule,
    ModelAssistedDrawResult,
    ModelAssistedStabilitySummary,
    audit_claim,
    audit_claim_tree,
    claim,
    claim_tree,
    threshold_decision,
)
from .comparison import (
    ComparisonItemResult,
    PairwiseComparisonResult,
    RobustComparisonReport,
    robust_comparison_report,
    robust_ranking_report,
)
from .data import DataDiagnostic, DataDiagnostics, GroupedProblem, from_dataframe
from .dowhy import (
    DoWhyRepresentationAudit,
    audit_dowhy_effects,
    dowhy_refutation_from_report,
)
from .environments import (
    BatchedCvxpyEnvironments,
    CvxpyEnvironments,
    CvxpyConstraintMetadata,
    CvxpyError,
    ConvexAdmissibleSet,
    FiniteEnvironments,
    LinearConstraint,
    LineSegment,
    LPError,
    ParameterizedCvxpyEnvironments,
    PolytopeEnvironments,
    PublicFiberSaturated,
    SupportFunctionBackend,
    SupportFunctionIntervalResult,
    SupportFunctionReport,
    SupportFunctionResult,
    SupportFunctionTargetInterval,
    cvxpy_constraint,
    eq,
    geq,
    leq,
    linear_constraint,
    support_function_report,
)
from .exports import (
    report_dataframes,
    report_tables,
    report_to_json,
    tables_to_dataframes,
)
from .frontier import (
    FrontierCandidateExplanation,
    FrontierCloseAlternative,
    FrontierScenarioResult,
    FrontierScreenedRefinement,
    FrontierSearchTrace,
    FrontierScenarioComparison,
    PublicRepresentationCandidate,
    PublicRepresentationFrontier,
    public_representation_frontier,
)
from .joint import (
    HiddenCompositionUncertaintyReport,
    HiddenCompositionUncertaintyRow,
    JointCell,
    JointDistributionDraw,
    NonparametricJointDistribution,
    UncertaintyMetricSummary,
    fit_joint_distribution,
    hidden_composition_uncertainty,
    joint_draw_records,
)
from .metrics import RowMetric, row_metric
from .partition import Partition, PartitionError
from .plugins import (
    PluginMetadata,
    PluginRegistry,
    PluginValidationIssue,
    PluginValidationReport,
    UpdateSupportPlugin,
    assert_valid_plugin,
    discover_plugins,
    get_plugin,
    list_plugins,
    plugin_compiler,
    plugin_metric,
    plugin_q_preset,
    plugin_report_profile,
    register_plugin,
    unregister_plugin,
    validate_plugin,
)
from .problem import FiniteProblem, TooManyPartitions
from .presets import (
    CvxpyAdmissibleSetSpec,
    QPreset,
    cvxpy_admissible_set_spec,
    q_bounded_shift,
    q_chi_square_budget,
    q_covariate_balance,
    q_fiber_support_floor,
    q_intersection,
    q_kl_budget,
    q_l2_budget,
    q_mahalanobis_budget,
    q_observed,
    q_saturated,
    q_tv_budget,
    q_wasserstein,
)
from .report import (
    CausalReportingStabilitySuite,
    EstimatorUncertaintyAdjustment,
    InteractionRefinementCandidate,
    InteractionRefinementReport,
    PublicDescentReport,
    PublicFiberDiagnostic,
    RefinementAttribution,
    RefinementAttributionReport,
    RefinementCandidate,
    RefinementCoalitionEvaluation,
    RefinementSensitivityCandidate,
    RefinementSensitivityReport,
    RefinementSensitivityRow,
    RefinementSensitivityScenario,
    SensitivityReport,
    SensitivityRow,
    SensitivitySummary,
    StatisticalUncertainty,
    WitnessCellShift,
    WitnessFiberShift,
    WitnessReport,
    attribute_refinement_ambiguity,
    audit_effects,
    causal_reporting_stability,
    public_descent_report,
    public_fiber_diagnostics,
    recommend_refinements,
    recommend_refinement_interactions,
    recommend_refinements_sensitivity,
    sensitivity_report,
    witness_report,
)
from .results import (
    AdequacyResult,
    CardinalGapResult,
    ConstraintDual,
    LeastSupportResult,
    TransportResult,
    UncertainLinearConfidenceCoreResult,
    Witness,
)
from .spec import AuditRun, AuditSpec, QSpec, run_audit
from .targets import (
    LinearTarget,
    MomentTransformTarget,
    ProcedureTarget,
    ProcedureTargetContext,
    RatioTarget,
    TargetCapabilities,
    TargetContract,
    UncertainLinearTarget,
    UnsupportedTarget,
    UnsupportedTargetError,
)

try:
    __version__ = version("updatesupport")
except PackageNotFoundError:
    __version__ = "0.0.0"

__all__ = [
    "__version__",
    # Claim-first surface.
    "claim",
    "audit_claim",
    "claim_tree",
    "audit_claim_tree",
    "ClaimSpec",
    "ClaimAudit",
    "ClaimNode",
    "ClaimNodeAudit",
    "ClaimTree",
    "ClaimTreeAudit",
    "ClaimRefinementRecommendation",
    "DecisionRule",
    "DecisionResult",
    "threshold_decision",
    # Data compilation and structured outputs.
    "from_dataframe",
    "GroupedProblem",
    "DataDiagnostic",
    "DataDiagnostics",
    "report_to_json",
    "report_tables",
    "report_dataframes",
    "tables_to_dataframes",
    # Lower-level evidence reports.
    "public_descent_report",
    "PublicDescentReport",
    "witness_report",
    "WitnessReport",
    "sensitivity_report",
    "SensitivityReport",
    "recommend_refinements",
    "recommend_refinement_interactions",
    "recommend_refinements_sensitivity",
    "attribute_refinement_ambiguity",
    "RefinementCandidate",
    "InteractionRefinementReport",
    "RefinementAttribution",
    "RefinementAttributionReport",
    "RefinementCoalitionEvaluation",
    "RefinementSensitivityReport",
    # Public representation design and claim repair.
    "certify_public_representation",
    "RepresentationStabilityCertificate",
    "public_representation_frontier",
    "PublicRepresentationFrontier",
    "PublicRepresentationCandidate",
    "breakdown_point",
    "BreakdownPointReport",
    "robust_comparison_report",
    "robust_ranking_report",
    "RobustComparisonReport",
    # Stress-test presets.
    "QPreset",
    "QSpec",
    "q_saturated",
    "q_observed",
    "q_bounded_shift",
    "q_tv_budget",
    "q_chi_square_budget",
    "q_kl_budget",
    "q_l2_budget",
    "q_covariate_balance",
    "q_mahalanobis_budget",
    "q_wasserstein",
    "q_fiber_support_floor",
    "q_intersection",
    "SupportFunctionBackend",
    "SupportFunctionResult",
    "SupportFunctionIntervalResult",
    "SupportFunctionTargetInterval",
    "SupportFunctionReport",
    "support_function_report",
    # Model-assisted and estimator handoff helpers.
    "fit_joint_distribution",
    "hidden_composition_uncertainty",
    "NonparametricJointDistribution",
    "HiddenCompositionUncertaintyReport",
    "audit_effects",
    "causal_reporting_stability",
    "CausalReportingStabilitySuite",
    "adapt_dataframe_effects",
    "adapt_doubleml_effects",
    "adapt_dowhy_effects",
    "adapt_econml_effects",
    "EstimatorAdapterResult",
    # Serializable specs and plugin hooks.
    "AuditSpec",
    "AuditRun",
    "run_audit",
    "PluginMetadata",
    "PluginRegistry",
    "UpdateSupportPlugin",
    "discover_plugins",
    "register_plugin",
    "unregister_plugin",
    "validate_plugin",
]
