"""Representation adequacy and transport-stability auditing in Python."""

from importlib.metadata import PackageNotFoundError, version

from .adapters import (
    EstimatorAdapterResult,
    adapt_dataframe_effects,
    adapt_doubleml_effects,
    adapt_dowhy_effects,
    adapt_econml_effects,
)
from .data import GroupedProblem, from_dataframe
from .dowhy import (
    DoWhyRepresentationAudit,
    audit_dowhy_effects,
    dowhy_refutation_from_report,
)
from .environments import (
    CvxpyEnvironments,
    CvxpyConstraintMetadata,
    CvxpyError,
    FiniteEnvironments,
    LinearConstraint,
    LineSegment,
    LPError,
    ParameterizedCvxpyEnvironments,
    PolytopeEnvironments,
    PublicFiberSaturated,
    cvxpy_constraint,
    eq,
    geq,
    leq,
    linear_constraint,
)
from .metrics import RowMetric, row_metric
from .partition import Partition, PartitionError
from .plugins import (
    PluginRegistry,
    UpdateSupportPlugin,
    discover_plugins,
    get_plugin,
    list_plugins,
    plugin_compiler,
    plugin_metric,
    plugin_q_preset,
    plugin_report_profile,
    register_plugin,
    unregister_plugin,
)
from .problem import FiniteProblem, TooManyPartitions
from .presets import (
    QPreset,
    q_bounded_shift,
    q_chi_square_budget,
    q_kl_budget,
    q_observed,
    q_saturated,
    q_tv_budget,
    q_wasserstein,
)
from .report import (
    CausalReportingStabilitySuite,
    PublicDescentReport,
    PublicFiberDiagnostic,
    RefinementCandidate,
    RefinementSensitivityCandidate,
    RefinementSensitivityReport,
    RefinementSensitivityRow,
    RefinementSensitivityScenario,
    SensitivityReport,
    SensitivityRow,
    SensitivitySummary,
    StatisticalUncertainty,
    audit_effects,
    causal_reporting_stability,
    public_descent_report,
    public_fiber_diagnostics,
    recommend_refinements,
    recommend_refinements_sensitivity,
    sensitivity_report,
)
from .results import (
    AdequacyResult,
    CardinalGapResult,
    ConstraintDual,
    LeastSupportResult,
    TransportResult,
    Witness,
)

try:
    __version__ = version("updatesupport")
except PackageNotFoundError:
    __version__ = "0.0.0"

__all__ = [
    "__version__",
    "AdequacyResult",
    "adapt_dataframe_effects",
    "adapt_doubleml_effects",
    "adapt_dowhy_effects",
    "adapt_econml_effects",
    "CardinalGapResult",
    "CausalReportingStabilitySuite",
    "ConstraintDual",
    "CvxpyEnvironments",
    "CvxpyConstraintMetadata",
    "CvxpyError",
    "cvxpy_constraint",
    "causal_reporting_stability",
    "DoWhyRepresentationAudit",
    "eq",
    "EstimatorAdapterResult",
    "audit_effects",
    "audit_dowhy_effects",
    "dowhy_refutation_from_report",
    "FiniteEnvironments",
    "FiniteProblem",
    "from_dataframe",
    "geq",
    "GroupedProblem",
    "leq",
    "LeastSupportResult",
    "LinearConstraint",
    "LineSegment",
    "linear_constraint",
    "LPError",
    "Partition",
    "PartitionError",
    "ParameterizedCvxpyEnvironments",
    "PluginRegistry",
    "PolytopeEnvironments",
    "PublicFiberSaturated",
    "PublicDescentReport",
    "PublicFiberDiagnostic",
    "public_descent_report",
    "public_fiber_diagnostics",
    "QPreset",
    "q_bounded_shift",
    "q_chi_square_budget",
    "q_kl_budget",
    "q_observed",
    "q_saturated",
    "q_tv_budget",
    "q_wasserstein",
    "RowMetric",
    "row_metric",
    "discover_plugins",
    "get_plugin",
    "list_plugins",
    "plugin_compiler",
    "plugin_metric",
    "plugin_q_preset",
    "plugin_report_profile",
    "recommend_refinements",
    "recommend_refinements_sensitivity",
    "register_plugin",
    "RefinementCandidate",
    "RefinementSensitivityCandidate",
    "RefinementSensitivityReport",
    "RefinementSensitivityRow",
    "RefinementSensitivityScenario",
    "SensitivityReport",
    "SensitivityRow",
    "SensitivitySummary",
    "StatisticalUncertainty",
    "sensitivity_report",
    "TooManyPartitions",
    "TransportResult",
    "unregister_plugin",
    "UpdateSupportPlugin",
    "Witness",
]
