"""Representation adequacy and transport-stability auditing in Python."""

from .data import GroupedProblem, from_dataframe
from .dowhy import (
    DoWhyRepresentationAudit,
    audit_dowhy_effects,
    dowhy_refutation_from_report,
)
from .environments import (
    CvxpyEnvironments,
    CvxpyConstraintMetadata,
    CvxpyError,
    FiniteEnvironments,
    LinearConstraint,
    LineSegment,
    LPError,
    ParameterizedCvxpyEnvironments,
    PolytopeEnvironments,
    PublicFiberSaturated,
    cvxpy_constraint,
    eq,
    geq,
    leq,
    linear_constraint,
)
from .partition import Partition, PartitionError
from .problem import FiniteProblem, TooManyPartitions
from .presets import (
    QPreset,
    q_bounded_shift,
    q_chi_square_budget,
    q_kl_budget,
    q_observed,
    q_saturated,
    q_tv_budget,
    q_wasserstein,
)
from .report import (
    CausalReportingStabilitySuite,
    PublicDescentReport,
    PublicFiberDiagnostic,
    RefinementCandidate,
    RefinementSensitivityCandidate,
    RefinementSensitivityReport,
    RefinementSensitivityRow,
    RefinementSensitivityScenario,
    SensitivityReport,
    SensitivityRow,
    SensitivitySummary,
    StatisticalUncertainty,
    audit_effects,
    causal_reporting_stability,
    public_descent_report,
    public_fiber_diagnostics,
    recommend_refinements,
    recommend_refinements_sensitivity,
    sensitivity_report,
)
from .results import (
    AdequacyResult,
    CardinalGapResult,
    ConstraintDual,
    LeastSupportResult,
    TransportResult,
    Witness,
)

__all__ = [
    "AdequacyResult",
    "CardinalGapResult",
    "CausalReportingStabilitySuite",
    "ConstraintDual",
    "CvxpyEnvironments",
    "CvxpyConstraintMetadata",
    "CvxpyError",
    "cvxpy_constraint",
    "causal_reporting_stability",
    "DoWhyRepresentationAudit",
    "eq",
    "audit_effects",
    "audit_dowhy_effects",
    "dowhy_refutation_from_report",
    "FiniteEnvironments",
    "FiniteProblem",
    "from_dataframe",
    "geq",
    "GroupedProblem",
    "leq",
    "LeastSupportResult",
    "LinearConstraint",
    "LineSegment",
    "linear_constraint",
    "LPError",
    "Partition",
    "PartitionError",
    "ParameterizedCvxpyEnvironments",
    "PolytopeEnvironments",
    "PublicFiberSaturated",
    "PublicDescentReport",
    "PublicFiberDiagnostic",
    "public_descent_report",
    "public_fiber_diagnostics",
    "QPreset",
    "q_bounded_shift",
    "q_chi_square_budget",
    "q_kl_budget",
    "q_observed",
    "q_saturated",
    "q_tv_budget",
    "q_wasserstein",
    "recommend_refinements",
    "recommend_refinements_sensitivity",
    "RefinementCandidate",
    "RefinementSensitivityCandidate",
    "RefinementSensitivityReport",
    "RefinementSensitivityRow",
    "RefinementSensitivityScenario",
    "SensitivityReport",
    "SensitivityRow",
    "SensitivitySummary",
    "StatisticalUncertainty",
    "sensitivity_report",
    "TooManyPartitions",
    "TransportResult",
    "Witness",
]
